/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author pawel
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    
    String labelPayed;
    String labelAmount;
    String labelBalance;
    
    public Print() {
        initComponents();
    }

    public Print(String amount, String payed, String balance, TableModel model) throws PrinterException {
        initComponents();
        
        this.labelAmount = amount;
        this.labelPayed = payed;
        this.labelBalance = balance;
        
        printTxt.setText(printTxt.getText()+ "__________________________________________\n");
        printTxt.setText(printTxt.getText()+ "_________________WSIZ POS_________________\n\n");
        printTxt.setText(printTxt.getText()+ "  Product " + "\t" + "Price" + "\t"+ " Total \n");
        
        for(int i = 0; i< model.getRowCount(); i++){
            String product = (String)model.getValueAt(i, 1);
            String price = (String)model.getValueAt(i, 2);
            int total = (int)model.getValueAt(i, 4);
            
            printTxt.setText(printTxt.getText()+"\n" + product + "\t" + price + "\t"+ total);
        }
        printTxt.setText(printTxt.getText()+ "\n\n__________________________________________\n" + "   Payed: " + payed +"\n");
        printTxt.setText(printTxt.getText()+ "   Pay: " + amount +"\n");
        printTxt.setText(printTxt.getText()+ "   Balance: " + balance +"\n");
        printTxt.setText(printTxt.getText()+ "__________________________________________\n");
        
        printTxt.print();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        printTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 400));

        printTxt.setColumns(20);
        printTxt.setRows(5);
        jScrollPane1.setViewportView(printTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea printTxt;
    // End of variables declaration//GEN-END:variables
}
